<?php

namespace Dafuer\GetOptGeneratorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectOptionRepository extends EntityRepository
{
}
